name: jetleaf_devtool
description: Development tooling module for JetLeaf â€” provides utilities for debugging, runtime inspection, and project automation.
version: 1.0.5

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_devtool
issue_tracker: https://github.com/jetleaf/jetleaf_devtool/issues
documentation: https://jetleaf.hapnium.com/docs/devtool

topics:
  - devtools
  - debugging
  - automation
  - jetleaf
  - inspection

keywords:
  - jetleaf
  - devtools
  - debugging
  - automation
  - inspection

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  source_gen: ^4.0.2
  analyzer: ^8.4.1
  build: ^4.0.2
  frontend_server_client: ^4.0.0
  path: ^1.9.1
  vm_service: ^15.0.2
  jetleaf_core: ^1.0.5
  jetleaf_lang: ^1.0.5
  jetleaf_logging: ^1.0.5
  jetleaf_utils: ^1.0.5

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0

executables:
  jl: jl